name: Worflow deploy
on:
  push:
    branches:
      - master
jobs:
  cancel_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access-token: ${{github.token }}
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
  
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  

  

