name: Worflow deploy
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
jobs:
  cancel_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access-token: ${{github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: make a project 🎩
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
  
  deploy:
    if: github.ref == 'refs/heads/master' & github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Deploy to Vercel Action 🎩
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}




